[package]
name = "nadir"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
scraper = "0.23.1"
serde_json = "1.0.140"
minify-html-onepass = "0.16.4"
colored = "3.0.0"
path-slash = "0.2.1"

